# Generated by Django 4.0.1 on 2023-06-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_prueba_ingles', '0003_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=600)),
            ],
        ),
    ]
