# Generated by Django 4.0.1 on 2023-06-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_prueba_ingles', '0004_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
