# Generated by Django 4.0.1 on 2023-06-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_prueba_ingles', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
    ]
